### ISSUE TITLE
Check if deleting users based on simple login log plugin's log file is working

### ISSUE THREAD

**Issue by sudar** [bulk-wp/bulk-delete#605]
Raised as a support ticket at https://wordpress.org/support/topic/do-not-work-delete-users/

**Comment by esudalaimadan** [comment]
@sudar, I tested login filter in my local and it works fine.
**Reason for failure mentioned in support ticket:**
That user has used two filters namely login filter and limit filter(please see the screenshot attached in support ticket). As we already know, we take (say first 100 users) and then when we apply login filter, all of the 100 users fail in login filter.  So it is deleting 0 users.

**Comment by sudar** [comment]
Thanks @esudalaimadan 

Closing this, since this is a duplicate of #511
